name: 'Trufflehog Check'
description: 'Scan for committed secrets with minimal configuration.'
runs:
  using: 'docker'
  image: 'Dockerfile'
inputs:
  branch:
    description: 'Branch to run the check on'
    required: false
outputs:
  result:
    description: 'Return scan results'
  status_code:
    description: '1 if secrets found, 0 otherwise'
branding:
  icon: 'lock'
  color: 'orange'
